#!/bin/bash

# Installs the required packages to run the Linux/MacOS desktop application

python3 -m venv venv
source venv/bin/activate
venv/bin/python3 -m pip install pip -U
venv/bin/pip3 install -r requirements.txt
