#!/bin/bash

# Installs the required packages to run the desktop application

python3.9 -m venv venv
source venv/bin/activate
venv/bin/python3.9 -m pip install pip -U
venv/bin/pip3 install -r requirements-cmd.txt
