#!/bin/bash

# Installs the required packages to run the commandline indexer and web server in Linux/MacOS

python3 -m venv venv
source venv/bin/activate
venv/bin/python3 -m pip install pip -U
venv/bin/pip3 install -r requirements-cmd.txt

