# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './stdb_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_stdbMainwindow(object):
    def setupUi(self, stdbMainwindow):
        stdbMainwindow.setObjectName(_fromUtf8("stdbMainwindow"))
        stdbMainwindow.resize(958, 659)
        self.centralwidget = QtGui.QWidget(stdbMainwindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dataDock = QtGui.QDockWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataDock.sizePolicy().hasHeightForWidth())
        self.dataDock.setSizePolicy(sizePolicy)
        self.dataDock.setMinimumSize(QtCore.QSize(400, 345))
        self.dataDock.setFloating(False)
        self.dataDock.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.dataDock.setObjectName(_fromUtf8("dataDock"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_3.setSizePolicy(sizePolicy)
        self.dockWidgetContents_3.setMinimumSize(QtCore.QSize(100, 100))
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 13)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.importFileButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importFileButton.sizePolicy().hasHeightForWidth())
        self.importFileButton.setSizePolicy(sizePolicy)
        self.importFileButton.setObjectName(_fromUtf8("importFileButton"))
        self.gridLayout.addWidget(self.importFileButton, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        self.optionsButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsButton.sizePolicy().hasHeightForWidth())
        self.optionsButton.setSizePolicy(sizePolicy)
        self.optionsButton.setObjectName(_fromUtf8("optionsButton"))
        self.gridLayout.addWidget(self.optionsButton, 11, 0, 1, 1)
        self.searchButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.gridLayout.addWidget(self.searchButton, 4, 0, 1, 1)
        self.importDirButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importDirButton.sizePolicy().hasHeightForWidth())
        self.importDirButton.setSizePolicy(sizePolicy)
        self.importDirButton.setObjectName(_fromUtf8("importDirButton"))
        self.gridLayout.addWidget(self.importDirButton, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.exportButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportButton.sizePolicy().hasHeightForWidth())
        self.exportButton.setSizePolicy(sizePolicy)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.gridLayout.addWidget(self.exportButton, 8, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.dockWidgetContents_3)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.importResults = QtGui.QWidget()
        self.importResults.setObjectName(_fromUtf8("importResults"))
        self.verticalLayout = QtGui.QVBoxLayout(self.importResults)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.relocate_lineEdit = QtGui.QLineEdit(self.importResults)
        self.relocate_lineEdit.setFrame(False)
        self.relocate_lineEdit.setObjectName(_fromUtf8("relocate_lineEdit"))
        self.verticalLayout.addWidget(self.relocate_lineEdit)
        self.cifList_treeWidget = QtGui.QTreeWidget(self.importResults)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.cifList_treeWidget.sizePolicy().hasHeightForWidth())
        self.cifList_treeWidget.setSizePolicy(sizePolicy)
        self.cifList_treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.cifList_treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.cifList_treeWidget.setObjectName(_fromUtf8("cifList_treeWidget"))
        self.verticalLayout.addWidget(self.cifList_treeWidget)
        self.properties_treeWidget = QtGui.QTreeWidget(self.importResults)
        self.properties_treeWidget.setObjectName(_fromUtf8("properties_treeWidget"))
        self.properties_treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.properties_treeWidget)
        self.stackedWidget.addWidget(self.importResults)
        self.refinement_edit_page = QtGui.QWidget()
        self.refinement_edit_page.setObjectName(_fromUtf8("refinement_edit_page"))
        self.stackedWidget.addWidget(self.refinement_edit_page)
        self.stackedWidgetPage2 = QtGui.QWidget()
        self.stackedWidgetPage2.setObjectName(_fromUtf8("stackedWidgetPage2"))
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 1, 1, 1)
        self.dataDock.setWidget(self.dockWidgetContents_3)
        self.horizontalLayout.addWidget(self.dataDock)
        stdbMainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(stdbMainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        stdbMainwindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(stdbMainwindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        stdbMainwindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(stdbMainwindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionEdit_dataset = QtGui.QAction(stdbMainwindow)
        self.actionEdit_dataset.setObjectName(_fromUtf8("actionEdit_dataset"))
        self.actionUser_manual = QtGui.QAction(stdbMainwindow)
        self.actionUser_manual.setObjectName(_fromUtf8("actionUser_manual"))
        self.actionImport_file = QtGui.QAction(stdbMainwindow)
        self.actionImport_file.setObjectName(_fromUtf8("actionImport_file"))
        self.actionImport_directory = QtGui.QAction(stdbMainwindow)
        self.actionImport_directory.setObjectName(_fromUtf8("actionImport_directory"))
        self.actionExport_Database_s = QtGui.QAction(stdbMainwindow)
        self.actionExport_Database_s.setObjectName(_fromUtf8("actionExport_Database_s"))
        self.actionOptions = QtGui.QAction(stdbMainwindow)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.fileMenu.addAction(self.actionExit)
        self.fileMenu.addAction(self.actionImport_file)
        self.fileMenu.addAction(self.actionImport_directory)
        self.fileMenu.addAction(self.actionExport_Database_s)
        self.fileMenu.addAction(self.actionOptions)
        self.menuEdit.addAction(self.actionEdit_dataset)
        self.menuHelp.addAction(self.actionUser_manual)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(stdbMainwindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(stdbMainwindow)

    def retranslateUi(self, stdbMainwindow):
        stdbMainwindow.setWindowTitle(_translate("stdbMainwindow", "MainWindow", None))
        self.importFileButton.setText(_translate("stdbMainwindow", "Open Database", None))
        self.optionsButton.setText(_translate("stdbMainwindow", "Options", None))
        self.searchButton.setText(_translate("stdbMainwindow", "Cell Search", None))
        self.importDirButton.setText(_translate("stdbMainwindow", "Import Directory", None))
        self.exportButton.setText(_translate("stdbMainwindow", "Export Database(s)", None))
        self.cifList_treeWidget.setSortingEnabled(True)
        self.cifList_treeWidget.headerItem().setText(0, _translate("stdbMainwindow", "file", None))
        self.cifList_treeWidget.headerItem().setText(1, _translate("stdbMainwindow", "dir", None))
        self.fileMenu.setTitle(_translate("stdbMainwindow", "File", None))
        self.menuEdit.setTitle(_translate("stdbMainwindow", "edit", None))
        self.menuHelp.setTitle(_translate("stdbMainwindow", "help", None))
        self.actionExit.setText(_translate("stdbMainwindow", "Exit", None))
        self.actionExit.setShortcut(_translate("stdbMainwindow", "Ctrl+Q", None))
        self.actionEdit_dataset.setText(_translate("stdbMainwindow", "edit dataset", None))
        self.actionUser_manual.setText(_translate("stdbMainwindow", "user manual", None))
        self.actionImport_file.setText(_translate("stdbMainwindow", "Import file", None))
        self.actionImport_directory.setText(_translate("stdbMainwindow", "Import directory", None))
        self.actionExport_Database_s.setText(_translate("stdbMainwindow", "Export Database(s)", None))
        self.actionOptions.setText(_translate("stdbMainwindow", "Options", None))

