#!/bin/bash

# Runs the StructureFinder Linux/MacOS desktop application

# Before running this script, you probably need to run './install_all_requirements'

source venv/bin/activate
export PYTHONPATH=.
python3 structurefinder/strf.py "$@"
