#!/bin/bash

# Runs the structurefinder commandline indexer in Linux/MacOS

# Before running this script, you probably need to run './install_min_requirements'

source venv/bin/activate
export PYTHONPATH=.
python3 src/structurefinder/strf_cmd.py "$@"
