#!/bin/bash

# Runs the StructureFinder web service in Linux/MacOS

# Before running this script, you probably need to run './install_min_requirements.bat'


source venv/bin/activate
export PYTHONPATH=.
python3 cgi_ui/strf_web.py "$@"

