# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/strf_main.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stdbMainwindow(object):
    def setupUi(self, stdbMainwindow):
        stdbMainwindow.setObjectName("stdbMainwindow")
        stdbMainwindow.resize(1128, 711)
        self.centralwidget = QtWidgets.QWidget(stdbMainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.importDirButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importDirButton.sizePolicy().hasHeightForWidth())
        self.importDirButton.setSizePolicy(sizePolicy)
        self.importDirButton.setObjectName("importDirButton")
        self.gridLayout.addWidget(self.importDirButton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 1)
        self.openApexDBButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openApexDBButton.sizePolicy().hasHeightForWidth())
        self.openApexDBButton.setSizePolicy(sizePolicy)
        self.openApexDBButton.setObjectName("openApexDBButton")
        self.gridLayout.addWidget(self.openApexDBButton, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.importDatabaseButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importDatabaseButton.sizePolicy().hasHeightForWidth())
        self.importDatabaseButton.setSizePolicy(sizePolicy)
        self.importDatabaseButton.setObjectName("importDatabaseButton")
        self.gridLayout.addWidget(self.importDatabaseButton, 2, 0, 1, 1)
        self.closeDatabaseButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeDatabaseButton.sizePolicy().hasHeightForWidth())
        self.closeDatabaseButton.setSizePolicy(sizePolicy)
        self.closeDatabaseButton.setObjectName("closeDatabaseButton")
        self.gridLayout.addWidget(self.closeDatabaseButton, 10, 0, 1, 1)
        self.saveDatabaseButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveDatabaseButton.sizePolicy().hasHeightForWidth())
        self.saveDatabaseButton.setSizePolicy(sizePolicy)
        self.saveDatabaseButton.setObjectName("saveDatabaseButton")
        self.gridLayout.addWidget(self.saveDatabaseButton, 8, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setAccessibleDescription("")
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.maintab = QtWidgets.QWidget()
        self.maintab.setObjectName("maintab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.maintab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.importResults = QtWidgets.QGridLayout()
        self.importResults.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.importResults.setObjectName("importResults")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.importResults.addItem(spacerItem4, 3, 0, 1, 1)
        self.cifList_treeWidget = QtWidgets.QTreeWidget(self.maintab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.cifList_treeWidget.sizePolicy().hasHeightForWidth())
        self.cifList_treeWidget.setSizePolicy(sizePolicy)
        self.cifList_treeWidget.setStatusTip("")
        self.cifList_treeWidget.setAutoFillBackground(False)
        self.cifList_treeWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cifList_treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.cifList_treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.cifList_treeWidget.setObjectName("cifList_treeWidget")
        self.cifList_treeWidget.header().setSortIndicatorShown(True)
        self.importResults.addWidget(self.cifList_treeWidget, 1, 0, 1, 1)
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.searchLayout.setSpacing(7)
        self.searchLayout.setObjectName("searchLayout")
        self.searchLabel = QtWidgets.QLabel(self.maintab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLabel.sizePolicy().hasHeightForWidth())
        self.searchLabel.setSizePolicy(sizePolicy)
        self.searchLabel.setObjectName("searchLabel")
        self.searchLayout.addWidget(self.searchLabel)
        self.searchCellLineEDit = QtWidgets.QLineEdit(self.maintab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.searchCellLineEDit.sizePolicy().hasHeightForWidth())
        self.searchCellLineEDit.setSizePolicy(sizePolicy)
        self.searchCellLineEDit.setObjectName("searchCellLineEDit")
        self.searchLayout.addWidget(self.searchCellLineEDit)
        self.moreResultsCheckBox = QtWidgets.QCheckBox(self.maintab)
        self.moreResultsCheckBox.setObjectName("moreResultsCheckBox")
        self.searchLayout.addWidget(self.moreResultsCheckBox)
        self.sublattCheckbox = QtWidgets.QCheckBox(self.maintab)
        self.sublattCheckbox.setObjectName("sublattCheckbox")
        self.searchLayout.addWidget(self.sublattCheckbox)
        self.line = QtWidgets.QFrame(self.maintab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.searchLayout.addWidget(self.line)
        self.txtSearchLabel = QtWidgets.QLabel(self.maintab)
        self.txtSearchLabel.setObjectName("txtSearchLabel")
        self.searchLayout.addWidget(self.txtSearchLabel)
        self.txtSearchEdit = QtWidgets.QLineEdit(self.maintab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txtSearchEdit.sizePolicy().hasHeightForWidth())
        self.txtSearchEdit.setSizePolicy(sizePolicy)
        self.txtSearchEdit.setObjectName("txtSearchEdit")
        self.searchLayout.addWidget(self.txtSearchEdit)
        self.importResults.addLayout(self.searchLayout, 0, 0, 1, 1)
        self.resultsGroupBox = QtWidgets.QGroupBox(self.maintab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.resultsGroupBox.sizePolicy().hasHeightForWidth())
        self.resultsGroupBox.setSizePolicy(sizePolicy)
        self.resultsGroupBox.setStyleSheet("")
        self.resultsGroupBox.setFlat(False)
        self.resultsGroupBox.setObjectName("resultsGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.resultsGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.resultsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(210, 0))
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cellField = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cellField.sizePolicy().hasHeightForWidth())
        self.cellField.setSizePolicy(sizePolicy)
        self.cellField.setMinimumSize(QtCore.QSize(0, 75))
        self.cellField.setBaseSize(QtCore.QSize(160, 75))
        self.cellField.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.cellField.setAutoFillBackground(False)
        self.cellField.setStyleSheet("border-color: rgb(53, 53, 53);")
        self.cellField.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cellField.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cellField.setText("")
        self.cellField.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cellField.setObjectName("cellField")
        self.gridLayout_5.addWidget(self.cellField, 1, 1, 1, 1)
        self.CellLabel = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CellLabel.setFont(font)
        self.CellLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.CellLabel.setObjectName("CellLabel")
        self.gridLayout_5.addWidget(self.CellLabel, 0, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.label = QtWidgets.QLabel(self.resultsGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.formLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.formLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formLabel.sizePolicy().hasHeightForWidth())
        self.formLabel.setSizePolicy(sizePolicy)
        self.formLabel.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(False)
        self.formLabel.setFont(font)
        self.formLabel.setAutoFillBackground(False)
        self.formLabel.setStyleSheet("background-color:  rgba(255, 255, 255, 255);")
        self.formLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.formLabel.setLineWidth(1)
        self.formLabel.setText("")
        self.formLabel.setTextFormat(QtCore.Qt.RichText)
        self.formLabel.setWordWrap(True)
        self.formLabel.setObjectName("formLabel")
        self.verticalLayout_6.addWidget(self.formLabel)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setObjectName("formLayout_2")
        self.reflTotalLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.reflTotalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reflTotalLabel.setObjectName("reflTotalLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.reflTotalLabel)
        self.reflTotalLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.reflTotalLineEdit.setReadOnly(True)
        self.reflTotalLineEdit.setObjectName("reflTotalLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.reflTotalLineEdit)
        self.uniqReflLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.uniqReflLabel.setObjectName("uniqReflLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.uniqReflLabel)
        self.uniqReflLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.uniqReflLineEdit.setObjectName("uniqReflLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uniqReflLineEdit)
        self.refl2sigmaLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.refl2sigmaLabel.setObjectName("refl2sigmaLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.refl2sigmaLabel)
        self.refl2sigmaLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.refl2sigmaLineEdit.setObjectName("refl2sigmaLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.refl2sigmaLineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.SpaceGrouplabel = QtWidgets.QLabel(self.resultsGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SpaceGrouplabel.setFont(font)
        self.SpaceGrouplabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SpaceGrouplabel.setObjectName("SpaceGrouplabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.SpaceGrouplabel)
        self.SpaceGroupLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.SpaceGroupLineEdit.setReadOnly(True)
        self.SpaceGroupLineEdit.setObjectName("SpaceGroupLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SpaceGroupLineEdit)
        self.zLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.zLabel.setObjectName("zLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.zLabel)
        self.zLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.zLineEdit.setReadOnly(True)
        self.zLineEdit.setObjectName("zLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.zLineEdit)
        self.temperatureLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.temperatureLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.temperatureLabel)
        self.temperatureLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.temperatureLineEdit.setReadOnly(True)
        self.temperatureLineEdit.setObjectName("temperatureLineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.temperatureLineEdit)
        self.wR2Label = QtWidgets.QLabel(self.resultsGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.wR2Label.setFont(font)
        self.wR2Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wR2Label.setObjectName("wR2Label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.wR2Label)
        self.wR2LineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.wR2LineEdit.setReadOnly(True)
        self.wR2LineEdit.setObjectName("wR2LineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.wR2LineEdit)
        self.r1Label = QtWidgets.QLabel(self.resultsGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.r1Label.setFont(font)
        self.r1Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.r1Label.setObjectName("r1Label")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.r1Label)
        self.r1LineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.r1LineEdit.setReadOnly(True)
        self.r1LineEdit.setObjectName("r1LineEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.r1LineEdit)
        self.goofLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.goofLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.goofLabel.setObjectName("goofLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.goofLabel)
        self.goofLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.goofLineEdit.setReadOnly(True)
        self.goofLineEdit.setObjectName("goofLineEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.goofLineEdit)
        self.maxShiftLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.maxShiftLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxShiftLabel.setObjectName("maxShiftLabel")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.maxShiftLabel)
        self.maxShiftLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.maxShiftLineEdit.setReadOnly(True)
        self.maxShiftLineEdit.setObjectName("maxShiftLineEdit")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.maxShiftLineEdit)
        self.peakLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.peakLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.peakLabel.setObjectName("peakLabel")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.peakLabel)
        self.peakLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.peakLineEdit.setReadOnly(True)
        self.peakLineEdit.setObjectName("peakLineEdit")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.peakLineEdit)
        self.rintLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.rintLineEdit.setReadOnly(True)
        self.rintLineEdit.setObjectName("rintLineEdit")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.rintLineEdit)
        self.rsigmaLabel = QtWidgets.QLabel(self.resultsGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rsigmaLabel.setFont(font)
        self.rsigmaLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rsigmaLabel.setObjectName("rsigmaLabel")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.rsigmaLabel)
        self.rsigmaLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.rsigmaLineEdit.setReadOnly(True)
        self.rsigmaLineEdit.setObjectName("rsigmaLineEdit")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.rsigmaLineEdit)
        self.rintLabel = QtWidgets.QLabel(self.resultsGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rintLabel.setFont(font)
        self.rintLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rintLabel.setObjectName("rintLabel")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.rintLabel)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.numParametersLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.numParametersLineEdit.setReadOnly(True)
        self.numParametersLineEdit.setObjectName("numParametersLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.numParametersLineEdit)
        self.dataReflnsLabel = QtWidgets.QLabel(self.resultsGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dataReflnsLabel.setFont(font)
        self.dataReflnsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dataReflnsLabel.setObjectName("dataReflnsLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dataReflnsLabel)
        self.numRestraintsLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.numRestraintsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numRestraintsLabel.setObjectName("numRestraintsLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.numRestraintsLabel)
        self.numRestraintsLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.numRestraintsLineEdit.setReadOnly(True)
        self.numRestraintsLineEdit.setObjectName("numRestraintsLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.numRestraintsLineEdit)
        self.thetaMaxLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.thetaMaxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.thetaMaxLabel.setObjectName("thetaMaxLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.thetaMaxLabel)
        self.thetaMaxLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.thetaMaxLineEdit.setReadOnly(True)
        self.thetaMaxLineEdit.setObjectName("thetaMaxLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.thetaMaxLineEdit)
        self.thetaFullLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.thetaFullLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.thetaFullLabel.setObjectName("thetaFullLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.thetaFullLabel)
        self.thetaFullLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.thetaFullLineEdit.setReadOnly(True)
        self.thetaFullLineEdit.setObjectName("thetaFullLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.thetaFullLineEdit)
        self.dLabel = QtWidgets.QLabel(self.resultsGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dLabel.setFont(font)
        self.dLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dLabel.setObjectName("dLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.dLabel)
        self.dLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.dLineEdit.setReadOnly(True)
        self.dLineEdit.setObjectName("dLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.dLineEdit)
        self.completeLabel = QtWidgets.QLabel(self.resultsGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.completeLabel.setFont(font)
        self.completeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.completeLabel.setObjectName("completeLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.completeLabel)
        self.completeLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.completeLineEdit.setReadOnly(True)
        self.completeLineEdit.setObjectName("completeLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.completeLineEdit)
        self.wavelengthLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.wavelengthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wavelengthLabel.setObjectName("wavelengthLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.wavelengthLabel)
        self.wavelengthLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.wavelengthLineEdit.setReadOnly(True)
        self.wavelengthLineEdit.setObjectName("wavelengthLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.wavelengthLineEdit)
        self.cCDCNumberLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.cCDCNumberLabel.setObjectName("cCDCNumberLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.cCDCNumberLabel)
        self.cCDCNumberLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.cCDCNumberLineEdit.setReadOnly(True)
        self.cCDCNumberLineEdit.setObjectName("cCDCNumberLineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.cCDCNumberLineEdit)
        self.numParametersLabel = QtWidgets.QLabel(self.resultsGroupBox)
        self.numParametersLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numParametersLabel.setObjectName("numParametersLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.numParametersLabel)
        self.dataReflnsLineEdit = QtWidgets.QLineEdit(self.resultsGroupBox)
        self.dataReflnsLineEdit.setReadOnly(True)
        self.dataReflnsLineEdit.setObjectName("dataReflnsLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dataReflnsLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.openglview = QtWidgets.QGroupBox(self.resultsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openglview.sizePolicy().hasHeightForWidth())
        self.openglview.setSizePolicy(sizePolicy)
        self.openglview.setAlignment(QtCore.Qt.AlignCenter)
        self.openglview.setFlat(False)
        self.openglview.setCheckable(False)
        self.openglview.setObjectName("openglview")
        self.ogllayout = QtWidgets.QVBoxLayout(self.openglview)
        self.ogllayout.setContentsMargins(0, 0, 0, 0)
        self.ogllayout.setSpacing(0)
        self.ogllayout.setObjectName("ogllayout")
        self.label_2 = QtWidgets.QLabel(self.openglview)
        self.label_2.setObjectName("label_2")
        self.ogllayout.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.openglview)
        self.importResults.addWidget(self.resultsGroupBox, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.importResults, 0, 0, 1, 1)
        self.tabWidget.addTab(self.maintab, "")
        self.allEntrysTab = QtWidgets.QWidget()
        self.allEntrysTab.setObjectName("allEntrysTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.allEntrysTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.allCifTreeWidget = QtWidgets.QTreeWidget(self.allEntrysTab)
        self.allCifTreeWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.allCifTreeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.allCifTreeWidget.setAllColumnsShowFocus(False)
        self.allCifTreeWidget.setObjectName("allCifTreeWidget")
        self.verticalLayout_7.addWidget(self.allCifTreeWidget)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.allEntrysTab, "")
        self.searchtab = QtWidgets.QWidget()
        self.searchtab.setObjectName("searchtab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.searchtab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.NotContainsLabel = QtWidgets.QLabel(self.searchtab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.NotContainsLabel.setFont(font)
        self.NotContainsLabel.setAutoFillBackground(False)
        self.NotContainsLabel.setStyleSheet("background-color: rgb(254, 201, 205);")
        self.NotContainsLabel.setTextFormat(QtCore.Qt.AutoText)
        self.NotContainsLabel.setObjectName("NotContainsLabel")
        self.gridLayout_6.addWidget(self.NotContainsLabel, 0, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ad_unitCellLineEdit = QtWidgets.QLineEdit(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_unitCellLineEdit.sizePolicy().hasHeightForWidth())
        self.ad_unitCellLineEdit.setSizePolicy(sizePolicy)
        self.ad_unitCellLineEdit.setObjectName("ad_unitCellLineEdit")
        self.gridLayout_4.addWidget(self.ad_unitCellLineEdit, 0, 1, 1, 1)
        self.ad_elementsIncLineEdit = QtWidgets.QLineEdit(self.searchtab)
        self.ad_elementsIncLineEdit.setObjectName("ad_elementsIncLineEdit")
        self.gridLayout_4.addWidget(self.ad_elementsIncLineEdit, 1, 1, 1, 1)
        self.unitCellLabel = QtWidgets.QLabel(self.searchtab)
        self.unitCellLabel.setObjectName("unitCellLabel")
        self.gridLayout_4.addWidget(self.unitCellLabel, 0, 0, 1, 1)
        self.ad_textsearch = QtWidgets.QLineEdit(self.searchtab)
        self.ad_textsearch.setObjectName("ad_textsearch")
        self.gridLayout_4.addWidget(self.ad_textsearch, 2, 1, 1, 1)
        self.elementsIncludedLabel = QtWidgets.QLabel(self.searchtab)
        self.elementsIncludedLabel.setObjectName("elementsIncludedLabel")
        self.gridLayout_4.addWidget(self.elementsIncludedLabel, 1, 0, 1, 1)
        self.wR2Label_2 = QtWidgets.QLabel(self.searchtab)
        self.wR2Label_2.setObjectName("wR2Label_2")
        self.gridLayout_4.addWidget(self.wR2Label_2, 2, 0, 1, 1)
        self.ad_moreResultscheckBox = QtWidgets.QCheckBox(self.searchtab)
        self.ad_moreResultscheckBox.setObjectName("ad_moreResultscheckBox")
        self.gridLayout_4.addWidget(self.ad_moreResultscheckBox, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem8, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.searchtab)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 0, 1, 3, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem9, 5, 2, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.wR2Label_3 = QtWidgets.QLabel(self.searchtab)
        self.wR2Label_3.setObjectName("wR2Label_3")
        self.gridLayout_7.addWidget(self.wR2Label_3, 2, 0, 1, 1)
        self.ad_elementsExclLineEdit = QtWidgets.QLineEdit(self.searchtab)
        self.ad_elementsExclLineEdit.setObjectName("ad_elementsExclLineEdit")
        self.gridLayout_7.addWidget(self.ad_elementsExclLineEdit, 1, 1, 1, 1)
        self.elementsExcludedLabel_2 = QtWidgets.QLabel(self.searchtab)
        self.elementsExcludedLabel_2.setObjectName("elementsExcludedLabel_2")
        self.gridLayout_7.addWidget(self.elementsExcludedLabel_2, 1, 0, 1, 1)
        self.ad_textsearch_excl = QtWidgets.QLineEdit(self.searchtab)
        self.ad_textsearch_excl.setObjectName("ad_textsearch_excl")
        self.gridLayout_7.addWidget(self.ad_textsearch_excl, 2, 1, 1, 1)
        self.unitCellLabel_2 = QtWidgets.QLabel(self.searchtab)
        self.unitCellLabel_2.setText("")
        self.unitCellLabel_2.setObjectName("unitCellLabel_2")
        self.gridLayout_7.addWidget(self.unitCellLabel_2, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 1, 2, 1, 1)
        self.ad_SearchPushButton = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_SearchPushButton.sizePolicy().hasHeightForWidth())
        self.ad_SearchPushButton.setSizePolicy(sizePolicy)
        self.ad_SearchPushButton.setMinimumSize(QtCore.QSize(150, 0))
        self.ad_SearchPushButton.setObjectName("ad_SearchPushButton")
        self.gridLayout_6.addWidget(self.ad_SearchPushButton, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ad_ShowAllButton = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_ShowAllButton.sizePolicy().hasHeightForWidth())
        self.ad_ShowAllButton.setSizePolicy(sizePolicy)
        self.ad_ShowAllButton.setMinimumSize(QtCore.QSize(150, 0))
        self.ad_ShowAllButton.setObjectName("ad_ShowAllButton")
        self.gridLayout_6.addWidget(self.ad_ShowAllButton, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.containsLabel = QtWidgets.QLabel(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.containsLabel.sizePolicy().hasHeightForWidth())
        self.containsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.containsLabel.setFont(font)
        self.containsLabel.setStyleSheet("background-color: rgb(173, 255, 167);")
        self.containsLabel.setObjectName("containsLabel")
        self.gridLayout_6.addWidget(self.containsLabel, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.searchtab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_6.addWidget(self.line_3, 3, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout_6)
        self.tabWidget.addTab(self.searchtab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        stdbMainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(stdbMainwindow)
        self.statusbar.setObjectName("statusbar")
        stdbMainwindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(stdbMainwindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUser_manual = QtWidgets.QAction(stdbMainwindow)
        self.actionUser_manual.setObjectName("actionUser_manual")
        self.actionImport_file = QtWidgets.QAction(stdbMainwindow)
        self.actionImport_file.setObjectName("actionImport_file")
        self.actionImport_directory = QtWidgets.QAction(stdbMainwindow)
        self.actionImport_directory.setObjectName("actionImport_directory")
        self.actionSave_Database = QtWidgets.QAction(stdbMainwindow)
        self.actionSave_Database.setObjectName("actionSave_Database")
        self.actionAdvanced_Search = QtWidgets.QAction(stdbMainwindow)
        self.actionAdvanced_Search.setObjectName("actionAdvanced_Search")
        self.actionAbout_StructureDB = QtWidgets.QAction(stdbMainwindow)
        self.actionAbout_StructureDB.setObjectName("actionAbout_StructureDB")
        self.actionClose_Database = QtWidgets.QAction(stdbMainwindow)
        self.actionClose_Database.setObjectName("actionClose_Database")
        self.actionCopy_Unit_Cell = QtWidgets.QAction(stdbMainwindow)
        self.actionCopy_Unit_Cell.setObjectName("actionCopy_Unit_Cell")
        self.actionGo_to_All_CIF_Tab = QtWidgets.QAction(stdbMainwindow)
        self.actionGo_to_All_CIF_Tab.setObjectName("actionGo_to_All_CIF_Tab")

        self.retranslateUi(stdbMainwindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(stdbMainwindow.close)
        QtCore.QMetaObject.connectSlotsByName(stdbMainwindow)
        stdbMainwindow.setTabOrder(self.importDirButton, self.importDatabaseButton)
        stdbMainwindow.setTabOrder(self.importDatabaseButton, self.openApexDBButton)
        stdbMainwindow.setTabOrder(self.openApexDBButton, self.saveDatabaseButton)
        stdbMainwindow.setTabOrder(self.saveDatabaseButton, self.closeDatabaseButton)
        stdbMainwindow.setTabOrder(self.closeDatabaseButton, self.tabWidget)
        stdbMainwindow.setTabOrder(self.tabWidget, self.cifList_treeWidget)
        stdbMainwindow.setTabOrder(self.cifList_treeWidget, self.searchCellLineEDit)
        stdbMainwindow.setTabOrder(self.searchCellLineEDit, self.moreResultsCheckBox)
        stdbMainwindow.setTabOrder(self.moreResultsCheckBox, self.txtSearchEdit)
        stdbMainwindow.setTabOrder(self.txtSearchEdit, self.SpaceGroupLineEdit)
        stdbMainwindow.setTabOrder(self.SpaceGroupLineEdit, self.zLineEdit)
        stdbMainwindow.setTabOrder(self.zLineEdit, self.temperatureLineEdit)
        stdbMainwindow.setTabOrder(self.temperatureLineEdit, self.wR2LineEdit)
        stdbMainwindow.setTabOrder(self.wR2LineEdit, self.r1LineEdit)
        stdbMainwindow.setTabOrder(self.r1LineEdit, self.goofLineEdit)
        stdbMainwindow.setTabOrder(self.goofLineEdit, self.maxShiftLineEdit)
        stdbMainwindow.setTabOrder(self.maxShiftLineEdit, self.peakLineEdit)
        stdbMainwindow.setTabOrder(self.peakLineEdit, self.rintLineEdit)
        stdbMainwindow.setTabOrder(self.rintLineEdit, self.rsigmaLineEdit)
        stdbMainwindow.setTabOrder(self.rsigmaLineEdit, self.numParametersLineEdit)
        stdbMainwindow.setTabOrder(self.numParametersLineEdit, self.dataReflnsLineEdit)
        stdbMainwindow.setTabOrder(self.dataReflnsLineEdit, self.numRestraintsLineEdit)
        stdbMainwindow.setTabOrder(self.numRestraintsLineEdit, self.thetaMaxLineEdit)
        stdbMainwindow.setTabOrder(self.thetaMaxLineEdit, self.thetaFullLineEdit)
        stdbMainwindow.setTabOrder(self.thetaFullLineEdit, self.dLineEdit)
        stdbMainwindow.setTabOrder(self.dLineEdit, self.completeLineEdit)
        stdbMainwindow.setTabOrder(self.completeLineEdit, self.wavelengthLineEdit)
        stdbMainwindow.setTabOrder(self.wavelengthLineEdit, self.cCDCNumberLineEdit)
        stdbMainwindow.setTabOrder(self.cCDCNumberLineEdit, self.allCifTreeWidget)
        stdbMainwindow.setTabOrder(self.allCifTreeWidget, self.ad_unitCellLineEdit)
        stdbMainwindow.setTabOrder(self.ad_unitCellLineEdit, self.ad_elementsIncLineEdit)
        stdbMainwindow.setTabOrder(self.ad_elementsIncLineEdit, self.ad_textsearch)
        stdbMainwindow.setTabOrder(self.ad_textsearch, self.ad_elementsExclLineEdit)
        stdbMainwindow.setTabOrder(self.ad_elementsExclLineEdit, self.ad_textsearch_excl)

    def retranslateUi(self, stdbMainwindow):
        _translate = QtCore.QCoreApplication.translate
        stdbMainwindow.setWindowTitle(_translate("stdbMainwindow", "StructureFinder"))
        self.importDirButton.setText(_translate("stdbMainwindow", "Import Directory"))
        self.openApexDBButton.setText(_translate("stdbMainwindow", "Open APEX Database"))
        self.importDatabaseButton.setText(_translate("stdbMainwindow", "Open Database File"))
        self.closeDatabaseButton.setText(_translate("stdbMainwindow", "Close Database"))
        self.saveDatabaseButton.setText(_translate("stdbMainwindow", "Save Database"))
        self.cifList_treeWidget.setSortingEnabled(True)
        self.cifList_treeWidget.headerItem().setText(0, _translate("stdbMainwindow", "Filename"))
        self.cifList_treeWidget.headerItem().setText(1, _translate("stdbMainwindow", "Data Name"))
        self.cifList_treeWidget.headerItem().setText(2, _translate("stdbMainwindow", "Directory"))
        self.cifList_treeWidget.headerItem().setText(3, _translate("stdbMainwindow", "Id"))
        self.searchLabel.setText(_translate("stdbMainwindow", "Cell Search:"))
        self.searchCellLineEDit.setToolTip(_translate("stdbMainwindow", "<html><head/><body><p>Insert unit cell as space separated <br/>numbers: <span style=\" font-style:italic;\">a b c α β γ</span></p></body></html>"))
        self.searchCellLineEDit.setPlaceholderText(_translate("stdbMainwindow", "a b c alpha beta gamma"))
        self.moreResultsCheckBox.setText(_translate("stdbMainwindow", "More results"))
        self.sublattCheckbox.setText(_translate("stdbMainwindow", "sub- or superlattice"))
        self.txtSearchLabel.setText(_translate("stdbMainwindow", "Search text:"))
        self.txtSearchEdit.setPlaceholderText(_translate("stdbMainwindow", "text in name, path or .res file"))
        self.resultsGroupBox.setTitle(_translate("stdbMainwindow", "Properties"))
        self.CellLabel.setText(_translate("stdbMainwindow", "Unit Cell:"))
        self.label.setText(_translate("stdbMainwindow", "Sum Formula:"))
        self.reflTotalLabel.setText(_translate("stdbMainwindow", "Total num. Refl."))
        self.uniqReflLabel.setText(_translate("stdbMainwindow", "Uniq Refl."))
        self.refl2sigmaLabel.setText(_translate("stdbMainwindow", "Refl. > 2sigma"))
        self.SpaceGrouplabel.setText(_translate("stdbMainwindow", "Space Group"))
        self.zLabel.setText(_translate("stdbMainwindow", "Z"))
        self.temperatureLabel.setText(_translate("stdbMainwindow", "Temperature [K]"))
        self.wR2Label.setText(_translate("stdbMainwindow", "wR2"))
        self.r1Label.setText(_translate("stdbMainwindow", "R1"))
        self.goofLabel.setText(_translate("stdbMainwindow", "Goof"))
        self.maxShiftLabel.setText(_translate("stdbMainwindow", "Max Shift/esd"))
        self.peakLabel.setText(_translate("stdbMainwindow", "<html><head/><body><p>Peak / Hole [eÅ<span style=\" vertical-align:super;\">-3</span>]</p></body></html>"))
        self.rsigmaLabel.setText(_translate("stdbMainwindow", "R(σ)"))
        self.rintLabel.setText(_translate("stdbMainwindow", "R(int)"))
        self.dataReflnsLabel.setText(_translate("stdbMainwindow", "data/param"))
        self.numRestraintsLabel.setText(_translate("stdbMainwindow", "Restraints"))
        self.thetaMaxLabel.setText(_translate("stdbMainwindow", "θ(max) [°]"))
        self.thetaFullLabel.setText(_translate("stdbMainwindow", "θ(full) [°]"))
        self.dLabel.setText(_translate("stdbMainwindow", "d [Å]"))
        self.completeLabel.setText(_translate("stdbMainwindow", "complete [%]"))
        self.wavelengthLabel.setText(_translate("stdbMainwindow", "Wavelength [Å]"))
        self.cCDCNumberLabel.setText(_translate("stdbMainwindow", "CCDC Number"))
        self.numParametersLabel.setText(_translate("stdbMainwindow", "Parameters"))
        self.label_2.setText(_translate("stdbMainwindow", "Asymmetric Unit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.maintab), _translate("stdbMainwindow", "Structures"))
        self.allCifTreeWidget.headerItem().setText(0, _translate("stdbMainwindow", "Keys"))
        self.allCifTreeWidget.headerItem().setText(1, _translate("stdbMainwindow", "Values"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.allEntrysTab), _translate("stdbMainwindow", "All cif values"))
        self.NotContainsLabel.setText(_translate("stdbMainwindow", "Should not contain"))
        self.unitCellLabel.setText(_translate("stdbMainwindow", "Unit Cell"))
        self.elementsIncludedLabel.setText(_translate("stdbMainwindow", "Elements"))
        self.wR2Label_2.setText(_translate("stdbMainwindow", "Any Text"))
        self.ad_moreResultscheckBox.setText(_translate("stdbMainwindow", "More Results"))
        self.wR2Label_3.setText(_translate("stdbMainwindow", "Any Text"))
        self.elementsExcludedLabel_2.setText(_translate("stdbMainwindow", "Elements"))
        self.ad_SearchPushButton.setText(_translate("stdbMainwindow", "Search"))
        self.ad_ShowAllButton.setText(_translate("stdbMainwindow", "Clear Search"))
        self.containsLabel.setText(_translate("stdbMainwindow", "Should contain"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.searchtab), _translate("stdbMainwindow", "Advanced Search"))
        self.actionExit.setText(_translate("stdbMainwindow", "Exit Program"))
        self.actionExit.setShortcut(_translate("stdbMainwindow", "Ctrl+Q"))
        self.actionUser_manual.setText(_translate("stdbMainwindow", "User Manual"))
        self.actionImport_file.setText(_translate("stdbMainwindow", "Open Database"))
        self.actionImport_directory.setText(_translate("stdbMainwindow", "Import Directory"))
        self.actionSave_Database.setText(_translate("stdbMainwindow", "Save Database"))
        self.actionAdvanced_Search.setText(_translate("stdbMainwindow", "Advanced Search"))
        self.actionAbout_StructureDB.setText(_translate("stdbMainwindow", "About StructureDB"))
        self.actionClose_Database.setText(_translate("stdbMainwindow", "Close Database"))
        self.actionCopy_Unit_Cell.setText(_translate("stdbMainwindow", "Copy Unit Cell"))
        self.actionGo_to_All_CIF_Tab.setText(_translate("stdbMainwindow", "Go to All CIF Tab"))
        self.actionGo_to_All_CIF_Tab.setShortcut(_translate("stdbMainwindow", "Meta+A"))

