# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='machine',
            new_name='number',
        ),
        migrations.AddField(
            model_name='machines',
            name='name',
            field=models.CharField(default='test', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
