; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "StructureFinder"
;#define MyAppVersion "74"  ; This is now done by commandline argument
#define MyAppPublisher "Daniel Kratzert"

; Remember, first run pyInstaller script!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FD3791DD-E642-47A6-8434-FBD976271019}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
; StructureFinder creates this mutex while it runs (see structurefinder/misc/selfupdate.py).
; Without it, Setup would try to replace loaded .pyd/.dll files of a running instance.
AppMutex=StructureFinderSetupMutex
; Machine-wide install (Program Files) by default. Pass /CURRENTUSER on the command line for a
; per-user install into {localappdata}\Programs\StructureFinder that needs no administrator rights, e.g.:
;   StructureFinder-setup-x64-vXXX.exe /CURRENTUSER /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
; /ALLUSERS forces the machine-wide install. {autopf} and {group} follow the selected mode.
; "dialog" lets users without administrator rights (restricted domain accounts) choose the
; per-user install in the Setup wizard instead of being stopped by the UAC prompt.
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=commandline dialog
UsePreviousPrivileges=yes
DefaultDirName={autopf}\{#MyAppName}
OutputBaseFilename={#MyAppName}-setup-x64-v{#MyAppVersion}
Compression=lzma2/fast
SolidCompression=yes
SetupLogging=True
CloseApplications=False
RestartApplications=False
ShowLanguageDialog=no
ChangesAssociations=True
RestartIfNeededByRun=False
ChangesEnvironment=True
DisableFinishedPage=True
DisableReadyPage=True
DisableReadyMemo=True
DisableWelcomePage=True
AlwaysShowDirOnReadyPage=True
InternalCompressLevel=fast
EnableDirDoesntExistWarning=True
DirExistsWarning=no
UninstallLogMode=new
VersionInfoVersion={#MyAppVersion}
MinVersion=10.0.10240
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
AppendDefaultGroupName=True
AppContact=dkratzert@gmx.de
AppCopyright=Daniel Kratzert
AppSupportPhone=+49 761 203 6156
VersionInfoProductName={#MyAppName}
AlwaysShowComponentsList=False
ShowComponentSizes=False
SetupIconFile="..\icons\strf.ico"
UninstallDisplayIcon={app}\{#MyAppName}.exe
SignTool=sign_sha256




[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

; adds a new page to the setup where you can choose if the path should be added
;Excludes: "*.pyc"

[Run]
; The VC++ redistributable is a machine-wide package and needs administrator rights, so it is only
; run for an /ALLUSERS (admin) install. For a /CURRENTUSER install the redistributable has to be
; deployed separately (it is part of every up to date Windows 10/11).
Filename: "{app}\vc_redist.x64.exe"; WorkingDir: "{app}"; Parameters: "/passive /norestart"; \
    Check: IsAdminInstallMode

[UninstallRun]

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\structurefinder.exe"; WorkingDir: "{app}"; IconFilename: "{app}\icons\strf.ico"; Check: IsWin64
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"; IconFilename: "{app}\icons\strf.ico"

[UninstallDelete]
Type: files; Name: "{app}\*.pyc"
; too dangerous:
;Type: files; Name: "{app}\*.*"
;Type: filesandordirs; Name: "{app}\*"
Type: filesandordirs; Name: "{app}\Lib"
Type: filesandordirs; Name: "{app}\Scripts"
Type: filesandordirs; Name: "{app}\icons"
Type: filesandordirs; Name: "{app}\structurefinder"
Type: filesandordirs; Name: "{app}\python*.*"

[InstallDelete]
;Type: filesandordirs; Name: "{app}\*"
Type: filesandordirs; Name: "{app}\Lib"
Type: filesandordirs; Name: "{app}\Scripts"
Type: filesandordirs; Name: "{app}\icons"
Type: filesandordirs; Name: "{app}\structurefinder"
Type: filesandordirs; Name: "{app}\python*.*"
; StructureFinder downloads and starts its installer itself, update.exe is not used anymore:
Type: files; Name: "{app}\update.exe"

[Tasks]

[Files]
; The environment is pre-compiled to legacy .pyc (see scripts/_make_win_release.py); *.py, *.pyi and the
; now redundant __pycache__ (never used for a sourceless import) are excluded below so the installer ships
; sourceless and slim. Only structurefinder\strf.py is kept, because the C launcher (structurefinder.exe)
; executes it as a source file.
Source: "..\src\structurefinder\*";            DestDir: "{app}\structurefinder"; Flags: ignoreversion createallsubdirs recursesubdirs; \
    Excludes: "*.py,*.pyi,__pycache__"
Source: "..\src\structurefinder\strf.py";      DestDir: "{app}\structurefinder"; Flags: ignoreversion
Source: "..\dist\python_dist\*";               DestDir: "{app}"; Flags: ignoreversion createallsubdirs recursesubdirs; \
    Excludes: "*.py,*.pyi,__pycache__"
Source: "..\icons\*";                          DestDir: "{app}\icons"; Flags: ignoreversion createallsubdirs recursesubdirs
Source: "..\structurefinder.exe";              DestDir: "{app}"; Flags: ignoreversion
Source: "..\vc_redist.x64.exe";                DestDir: "{app}"; Flags: ignoreversion

[Dirs]
;Name: "{app}\displaymol"; Permissions: everyone-full
;Name: "{app}\gui"; Permissions: everyone-full

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
// This procedure deletes the installer executable when it
// is named 'update-structurefinder.exe'
var
  strContent: String;
  intErrorCode: Integer;
  strSelf_Delete_BAT: String;
begin
  // Pos == str.contains(x)
  if Pos('update-structurefinder.exe', ExpandConstant('{srcexe}')) > 0 then
    begin
    if CurStep=ssDone then
    begin
      strContent := ':try_delete' + #13 + #10 +
            'del "' + ExpandConstant('{srcexe}') + '"' + #13 + #10 +
            'if exist "' + ExpandConstant('{srcexe}') + '" goto try_delete' + #13 + #10 +
            'del %0';

      strSelf_Delete_BAT := ExtractFilePath(ExpandConstant('{tmp}')) + 'SelfDelete.bat';
      SaveStringToFile(strSelf_Delete_BAT, strContent, False);
      Exec(strSelf_Delete_BAT, '', '', SW_HIDE, ewNoWait, intErrorCode);
    end;
  end;
end;
