# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flask_name', models.CharField(max_length=200)),
                ('machine', models.CharField(max_length=200)),
                ('operator', models.CharField(max_length=200)),
                ('measure_date', models.DateTimeField(verbose_name='date measured')),
            ],
        ),
        migrations.CreateModel(
            name='RefineResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_a', models.FloatField(default=0, max_length=8)),
                ('cell_b', models.FloatField(default=0, max_length=8)),
                ('cell_c', models.FloatField(default=0, max_length=8)),
                ('struct_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdb.Dataset')),
            ],
        ),
    ]
