# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refineresult',
            name='dataset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stdb.Dataset'),
        ),
        migrations.AlterField(
            model_name='refineresult',
            name='struct_name',
            field=models.CharField(max_length=200),
        ),
    ]
