# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0002_auto_20160513_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_a', models.FloatField(default=0, max_length=8)),
                ('cell_b', models.FloatField(default=0, max_length=8)),
                ('cell_c', models.FloatField(default=0, max_length=8)),
                ('cell_alpha', models.FloatField(default=0, max_length=8)),
                ('cell_beta', models.FloatField(default=0, max_length=8)),
                ('cell_gamma', models.FloatField(default=0, max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='refineresult',
            name='cell_a',
        ),
        migrations.RemoveField(
            model_name='refineresult',
            name='cell_b',
        ),
        migrations.RemoveField(
            model_name='refineresult',
            name='cell_c',
        ),
        migrations.RemoveField(
            model_name='refineresult',
            name='struct_name',
        ),
        migrations.AddField(
            model_name='refineresult',
            name='unit_cell',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stdb.UnitCell'),
        ),
    ]
