# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0003_auto_20160514_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refineresult',
            name='unit_cell',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='stdb.UnitCell'),
        ),
    ]
