# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0005_remove_refineresult_unit_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='refineresult',
            name='unit_cell',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stdb.UnitCell'),
        ),
    ]
