# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0009_auto_20160514_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refineresult',
            old_name='unit_cell',
            new_name='cell',
        ),
    ]
