# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0010_auto_20160514_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitcell',
            name='dataset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stdb.Dataset'),
        ),
        migrations.AlterField(
            model_name='refineresult',
            name='cell',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stdb.UnitCell'),
        ),
    ]
