# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0011_auto_20160514_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitcell',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='refineresult',
            name='cell',
        ),
        migrations.AddField(
            model_name='refineresult',
            name='cell_a',
            field=models.FloatField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='refineresult',
            name='cell_alpha',
            field=models.FloatField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='refineresult',
            name='cell_b',
            field=models.FloatField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='refineresult',
            name='cell_beta',
            field=models.FloatField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='refineresult',
            name='cell_c',
            field=models.FloatField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='refineresult',
            name='cell_gamma',
            field=models.FloatField(default=0, max_length=8),
        ),
        migrations.DeleteModel(
            name='UnitCell',
        ),
    ]
