# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 22:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0012_auto_20160514_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='crystal_size_x',
            field=models.FloatField(default=0, max_length=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='dataset',
            name='crystal_size_y',
            field=models.FloatField(default=0, max_length=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='dataset',
            name='crystal_size_z',
            field=models.FloatField(default=0, max_length=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='refineresult',
            name='cell_a',
            field=models.FloatField(default=0, max_length=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='refineresult',
            name='cell_alpha',
            field=models.FloatField(default=0, max_length=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='refineresult',
            name='cell_b',
            field=models.FloatField(default=0, max_length=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='refineresult',
            name='cell_beta',
            field=models.FloatField(default=0, max_length=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='refineresult',
            name='cell_c',
            field=models.FloatField(default=0, max_length=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='refineresult',
            name='cell_gamma',
            field=models.FloatField(default=0, max_length=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
