# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0013_auto_20160514_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refineresult',
            old_name='cell_a',
            new_name='a',
        ),
    ]
