# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 22:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0014_auto_20160514_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refineresult',
            name='a',
        ),
        migrations.AddField(
            model_name='refineresult',
            name='cell_a',
            field=models.FloatField(default=0, max_length=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='a'),
        ),
    ]
