# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdb', '0015_auto_20160514_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='refineresult',
            name='is_publishable',
            field=models.BooleanField(default=False),
        ),
    ]
