name: publish
on:
  push:
    tags:
      - '*'
jobs:
  tests:
    uses: ./.github/workflows/python_tests.yml
  build:
    needs: [ 'tests' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13

      - run: |
          uv sync --build
          uv build

      - uses: actions/upload-artifact@v7
        with:
          path: ./dist

  pypi-publish:
    needs: [ 'build' ]
    name: publish
    runs-on: ubuntu-latest
    environment:
      name: publish
      url: https://pypi.org/p/structurefinder
    permissions:
      contents: read
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v8
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: artifact/