on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: python.exe -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: pip install pyinstaller
    - run: pyinstaller StructureFinder.spec --clean -y
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*
        name: structurefinder-test-release
        retention-days: 7