on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - run: pip install pip -U
    - run: pip install -r requirements.txt
    - run: pip install pyinstaller
    - run: rmdir /S dist /Q
    - run: pyinstaller StructureFinder.spec --clean -y
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*